### ISSUE TITLE
Create Reusable GitHub Action for Godot Project Building and Publishing

### ISSUE THREAD

**Issue by digiur** [digiur/digiur-net#2]
Create a generalized GitHub Action for building and publishing Godot projects that can be easily added to any Godot project repository.

## Requirements
- [ ] Support both building Godot engine from source and downloading pre-built releases
- [ ] Automatic build of Godot projects
- [ ] Support for multiple publishing platforms (starting with itch.io)
- [ ] Configurable build parameters
- [ ] Cross-platform support

### 1. Action Configuration
Create a composite action that accepts the following inputs:
- `godot-version`: Version of Godot to use
- `build-from-source`: Boolean to determine if we should build Godot from source
- `export-preset`: The export preset to use
- `publish-targets`: Array of publishing platforms (e.g., "itch.io", "steam")
- `project-path`: Path to the Godot project (defaults to root)

### 2. Core Features
1. **Godot Setup**
   - If building from source:
     - Clone Godot repository at specified version
     - Build engine with necessary modules
   - If using pre-built:
     - Download specified version from GitHub releases
     - Set up export templates

2. **Project Building**
   - Validate project structure
   - Execute build process using specified preset
   - Handle build artifacts

3. **Publishing**
   - Implement modular publishing system
   - Start with itch.io support
   - Structure for easy addition of new platforms

### 3. Best Practices
- Use GitHub Actions cache for build artifacts
- Implement proper error handling and logging
- Add comprehensive documentation
- Include examples for common use cases

### 4. Current example improvements
```yaml
name: Godot Build and Publish
on:
  workflow_call:
    inputs:
      godot-version:
        required: true
        type: string
      build-from-source:
        required: false
        type: boolean
        default: false
      export-preset:
        required: true
        type: string
      publish-target:
        required: true
        type: string
    secrets:
      ITCHIO_API_KEY:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Godot
        id: setup-godot
        uses: ./.github/actions/setup-godot
        with:
          version: ${{ inputs.godot-version }}
          build-from-source: ${{ inputs.build-from-source }}
          
      - name: Build Project
        uses: ./.github/actions/build-godot-project
        with:
          godot-path: ${{ steps.setup-godot.outputs.godot-path }}
          export-preset: ${{ inputs.export-preset }}
          
      - name: Publish
        uses: ./.github/actions/publish
        with:
          target: ${{ inputs.publish-target }}
          artifacts-path: ./builds
          api-key: ${{ secrets.ITCHIO_API_KEY }}
```

## Next Steps
1. Create basic action structure
2. Implement Godot setup logic
3. Add project building functionality
4. Create publishing module starting with itch.io
5. Add documentation and examples
6. Test with various Godot projects

## Resources
- [GitHub Actions Documentation](https://docs.github.com/en/actions)
- [Godot Engine Build Instructions](https://docs.godotengine.org/en/stable/development/compiling/)
- [itch.io Butler Documentation](https://itch.io/docs/butler/)

Would you like to contribute to this project? Please feel free to comment with suggestions or improvements!
